# (Example) Optimization using Matryoshka
all:
	julia -e "using Matryoshka; Matryoshka.configuration_load(\"matryoshka_ex.json\"); Matryoshka.execute()" --startup-file=no

clean:
	rm -f *csv *log *png
